param(
    [switch]$IncludeSourceCheckoutDb,
    [switch]$IncludeUserState,
    [switch]$IncludeReleaseArtifacts
)

$ErrorActionPreference = "Stop"

$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Set-Location $ProjectRoot

function Remove-SqliteFamily {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    foreach ($Candidate in @(
        $Path,
        "$Path-wal",
        "$Path-shm",
        "$Path-journal"
    )) {
        if (Test-Path $Candidate -PathType Leaf) {
            Write-Host "REMOVE $Candidate"
            Remove-Item -Force $Candidate
        }
    }
}

function Remove-FileIfPresent {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if (Test-Path $Path -PathType Leaf) {
        Write-Host "REMOVE $Path"
        Remove-Item -Force $Path
    }
}

Write-Host
Write-Host "============================================"
Write-Host " EverQuestie Knowledge Build Cleanup"
Write-Host "============================================"
Write-Host
Write-Host "Project: $ProjectRoot"
Write-Host

# Canonical full-build databases.
$WorkingDb = Join-Path $ProjectRoot "build\working.sqlite3"
$BuildingDb = "$WorkingDb.building"
$SnapshotDb = Join-Path $ProjectRoot "dist\everquestie-knowledge.sqlite3"

Remove-SqliteFamily $WorkingDb
Remove-SqliteFamily $BuildingDb
Remove-SqliteFamily $SnapshotDb

# Full-build reports. These are regenerated by tools\build_full_knowledge.ps1.
foreach ($Relative in @(
    "build\allakhazam-temporary-page-audit.json",
    "build\allakhazam-mirror-audit.json",
    "build\allakhazam-normalization-delta.json",
    "build\map-catalog-audit.json",
    "build\route-acceptance.json",
    "build\provider-travel-frontier.json",
    "build\profile-lifecycle-audit.json"
)) {
    Remove-FileIfPresent (Join-Path $ProjectRoot $Relative)
}

if ($IncludeReleaseArtifacts) {
    foreach ($Relative in @(
        "build\release-working.sqlite3",
        "dist\everquestie-knowledge.sqlite3.sha256"
    )) {
        Remove-SqliteFamily (Join-Path $ProjectRoot $Relative)
        Remove-FileIfPresent (Join-Path $ProjectRoot $Relative)
    }

    $ReleaseRoot = Join-Path $ProjectRoot "build\release"
    if (Test-Path $ReleaseRoot -PathType Container) {
        Write-Host "REMOVE $ReleaseRoot"
        Remove-Item -Recurse -Force $ReleaseRoot
    }
}

$UserRoot = Join-Path $HOME ".eqquest"

if ($IncludeSourceCheckoutDb) {
    # Source-checkout/developer mode uses this legacy combined mutable DB.
    Remove-SqliteFamily (Join-Path $UserRoot "eqquest.sqlite3")
}

if ($IncludeUserState) {
    # Packaged runtime player state. Deliberately opt-in because this erases tracked
    # quest progress, observed-event history, runtime bindings, and other user state.
    Remove-SqliteFamily (Join-Path $UserRoot "everquestie-user.sqlite3")
}

Write-Host
Write-Host "Cleanup complete."
Write-Host "Builder inputs were NOT deleted:"
Write-Host "  - Allakhazam HTTrack mirror"
Write-Host "  - EverQuest installation"
Write-Host "  - everquest1-mcp checkout"
Write-Host "  - Good/Brewall map packs"
Write-Host "  - settings.ini"
Write-Host
Write-Host "Fresh full build:"
Write-Host "  .\tools\build_full_knowledge.ps1"
